### ISSUE TITLE
Sass version

### ISSUE THREAD

**Issue by doot0** [trello/trellisheets#2]
Is a Sass port on the roadmap for this project?

**Comment by nachiketkumar** [comment]
I created a sass port locally, just having a little trouble with getting the media queries to work. Not a front-end dev here, so I'd appreciate help from someone a little more sass proficient! I will create a PR.

**Comment by nachiketkumar** [comment]
I have a [sass port](https://github.com/nachiketkumar/trellisheets/tree/sass-port) mostly working except for some issues with media-queries and errors. Fixed by commenting out the media queries but would appreciate help from someone more proficient than I.

**Comment by bobbygrace** [comment]
An official sass port is not on the roadmap, but if a good fork comes along, I would be happy to link to it.
