### ISSUE TITLE
Component layout in structure

### ISSUE THREAD

**Issue by XOP** [trello/trellisheets#3]
Following the comment to [corresponding gist](https://gist.github.com/bobbygrace/9e961e8982f42eb91b80):

My proposition is about using specific syntax for component layout. Namely this:

``` scss
// Usage:
// <div class="component">
//   <p class="component-decendant">
//     <span class="component-decendant-descendant"></span>
//   </p>
// </div>
//
// (How it's used.)
```

I've come up with another way of illustrating component structure, that should be transparent enough.
This resulted in the project; you can find the documentation [here](http://cssg.rocks/docs/basic.html).

And [here](https://github.com/XOP/css-codeguide/blob/master/example/_component-1.scss) is the practical example of some sort.

So the previous code could be re-written as this:

``` scss
/* cssg

    component
        component-descendant
            component-descendant-descendant

*/

// all other code
```

There are some points backing this stuff:
- html can be generated differently (jade, react, handlebars, ...), it is possible to write it once in css, but after some changes maintaining can become a problem (talking about 113 components ;))
- in CSSG approach you illustrate all possible mods and states of component, not only one
- it's easier to read and grasp the structure at a glance
- easier to refactor and share snippets with colleagues

I'd like to take it to the next level actually and make a common thing between CSS-engaged front-end teams. Hope you'll find it useful as well!

**Comment by bobbygrace** [comment]
@XOP That's nice and clean, but it seems like standard HTML is a better way to communicate the structure than any given DSL, even a nice one like cssg.
